kind: pipeline
type: docker
name: vue-deploy

steps:
  - name: install
    image: node:20
    commands:
      - npm ci

  - name: lint
    image: node:20
    commands:
      - npm run lint
    depends_on:
      - install

  - name: build
    image: node:20
    commands:
      - npm run build-staging
    depends_on:
      - lint

  - name: deploy
    image: ubuntu:24.04
    commands:
      - apt-get update
      - apt-get install -y openssh-client rsync libssl-dev
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --delete -e "ssh -p $STAGING_SSH_PORT" ./dist/ $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_PATH
    environment:
      SSH_PRIVATE_KEY:
        from_secret: staging_ssh_key
      STAGING_SSH_PORT:
        from_secret: staging_ssh_port
      STAGING_SSH_HOST:
        from_secret: staging_ssh_host
      STAGING_SSH_USER:
        from_secret: staging_ssh_user
      STAGING_PATH:
        from_secret: staging_path
    depends_on:
      - build

trigger:
  branch:
    - main